- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Set timezone to Africa/Lagos
      community.general.timezone:
        name: Africa/Lagos

- vars:
    - task_name: "Install cURL"
    - package_name: "curl"
    - package_state: "present"
  hosts: "all"
  become: true

    - name: Allow www Full rule
      ufw:
        rule: allow
        name: "www Full"
    
    - name: Delete OpenSSH rule
      ufw:
        rule: allow
        name: OpenSSH
        delete: yes

    - name: enable ufw
      ufw: state=enabled policy=allow

    - name: Run a psql bash script 
      ansible.builtin.script: /psql/psql-install.sh

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: php

#- hosts: all
#  become: true
#  become_user: root
#  gather_facts: false
#  tasks:
#    - include_role:
#        name: cert
