- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Set timezone to Africa/Lagos
      community.general.timezone:
        name: Africa/Lagos

- vars:
    - task_name: "Install cURL"
    - package_name: "curl"
    - package_state: "present"
  hosts: "all"
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: "{{ task_name }} (UNIX)"
      package:
        name: "{{ package_name }}"
        state: "{{ package_state }}"

    - name: install UFW - Uncomplicated Firewall
      apt: name=ufw state=latest update_cache=yes

    - name: set logging
      ufw: logging=on

    - name: allow port 22
      ufw: rule=allow port=22

    - name: allow port 80
      ufw: rule=allow port=80

    - name: Allow SSH rule
      ufw:
        rule: allow
        name: SSH
        delete: yes

    - name: Allow OpenSSH rule
      ufw:
        rule: allow
        name: OpenSSH
        delete: yes

    - name: Allow www Full rule
      ufw:
        rule: allow
        name: "www Full"
        delete: yes

    - name: enable ufw
      ufw: state=enabled policy=allow

    - name: Run a psql bash script 
      ansible.builtin.script: /psql/psql-install.sh

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: php

#- hosts: all
#  become: true
#  become_user: root
#  gather_facts: false
#  tasks:
#    - include_role:
#        name: cert
