- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Installation install software-properties-common
  apt: name=software-properties-common

- name: "Repo PHP 7.4"
  apt_repository:
    repo="ppa:ondrej/php"
   
- name: "Updating the repo"
  apt: update_cache=yes

- name: Installation PHP 7.4
  apt: name=php7.4 state=present

- name: install lamp stack
  apt:
    pkg:
      - php7.4-mysql
      - php7.4-curl
      - php7.4-json
      - php7.4-cgi
      - php7.4-xsl
      - php7.4-cgi
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-zip
      - php7.4-xmlrpc
      - php7.4-soap
      - php7.4-intl
      - libapache2-mod-php
    state: present
    update_cache: yes 

- name: Install unzip
  apt: name=unzip state=latest


- name: Download php-composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Make composer executable
  file: 
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: install apache2 server
  apt:
     name: apache2
     state: present

- name: checkout latest code from github
  git: >
    repo=https://github.com/f1amy/laravel-realworld-example-app.git
    dest=/opt/{{ vhost_name }}
    force=yes
    accept_hostkey=yes

- name: copy lavarel project
  shell: sudo mv /opt/{{ vhost_name }} /var/www/html/

- name: Change permission
  shell: sudo chgrp -R www-data /var/www/html/{{ vhost_name }}/

- name: Change permission
  shell: sudo chmod -R 775 /var/www/html/{{ vhost_name }}/storage

- name: Remove default apache vhost config from sites-enabled
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Create apache vhosts for  domain
  template: src=web.conf.j2 dest="/etc/apache2/sites-available/{{ vhost_name }}.conf" owner=www-data group=www-data mode=0644

- name: Update a2ensite
  command: a2ensite {{ vhost_name }}

- name: Enable the Apache rewrite module
  command:  a2enmod rewrite

  notify:
    - restart apache2
